In [2]:
import numpy as np

a = np.array([100,101,102,103])
a

array([100, 101, 102, 103])

In [3]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [17]:
b = np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [13]:
# Indexing Multidimensional arrays
b[0,1] # same as b[(0,1)]

2

In [22]:
#write a np.array of shape (2,3,4)
c = np.array([[[1,21,2,44],[0,-1,0,4],[1,-1.,2.,10]],[[1,8,3,4],[9,-1,0.,4],[20,-1.,2.,0]]])
c.ndim

3

In [23]:
c[0,0,1]

21.0

In [24]:
b[1,1]= 10 # also for assignment
b

array([[ 1,  2],
       [ 3, 10]])

In [26]:
np.array([0,4,-4], dtype = complex)

array([ 0.+0.j,  4.+0.j, -4.+0.j])

In [27]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
x = np.zeros((4,2,3)) # default dtype is 'float'
x.shape
print(x)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [47]:
y = np.zeros((4,3), dtype = int)
print(y)
g = np.zeros((2,3,4)) # Why to give two paranthesis, when it is already a function?
print(g)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [32]:
a

array([100, 101, 102, 103])

In [42]:
np.ones_like(g) * 10 # Similar to a with 1

array([[10., 10., 10.],
       [10., 10., 10.]])

In [43]:
np.zeros_like(y, dtype = float) # how is this knowing the dimension of the matrix?

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.arange?

In [45]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [49]:
#Initializing an array from a sequence
# np.arange() - the NumPy equivalent of range, except that it can generate floating-point sequences.
# np.linspace() - more useful way of creating an sequence with given length

list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [50]:
np.arange(1.5, 4, 0.5) # Generate a sequence starting with 1.5 with width 0.5 and excluding 4

array([1.5, 2. , 2.5, 3. , 3.5])

In [52]:
np.linspace?

In [57]:
np.linspace(1,10,5, retstep = False)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [60]:
x = np.linspace(0,200,100,retstep = True)
#dx #dx  = (end-start)/(num-1) = 2*pi/99 = 0.0634665...
print(x)

(array([  0.        ,   2.02020202,   4.04040404,   6.06060606,
         8.08080808,  10.1010101 ,  12.12121212,  14.14141414,
        16.16161616,  18.18181818,  20.2020202 ,  22.22222222,
        24.24242424,  26.26262626,  28.28282828,  30.3030303 ,
        32.32323232,  34.34343434,  36.36363636,  38.38383838,
        40.4040404 ,  42.42424242,  44.44444444,  46.46464646,
        48.48484848,  50.50505051,  52.52525253,  54.54545455,
        56.56565657,  58.58585859,  60.60606061,  62.62626263,
        64.64646465,  66.66666667,  68.68686869,  70.70707071,
        72.72727273,  74.74747475,  76.76767677,  78.78787879,
        80.80808081,  82.82828283,  84.84848485,  86.86868687,
        88.88888889,  90.90909091,  92.92929293,  94.94949495,
        96.96969697,  98.98989899, 101.01010101, 103.03030303,
       105.05050505, 107.07070707, 109.09090909, 111.11111111,
       113.13131313, 115.15151515, 117.17171717, 119.19191919,
       121.21212121, 123.23232323, 125.25252525, 127.2

In [61]:
x = np.linspace(0, 5, 10, endpoint = False) # endpoint to False omits the final point in the sequence, as for np.arrange
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [68]:
#Initializing an Array from a Function
# def f(i,j):
#     return 2*i*j

np.fromfunction(f,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [64]:
np.fromfunction?

In [72]:
np.fromfunction(lambda i,j : 2*i*j,(4,3))    #Did not understand the fromfunction()

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [74]:
#create a "comb" of values in an array of length N for which every nth element is one but with zeros everywhere else
N, n = 20, 5
def f(i):
    return (i % n == 0) * 1

comb = np.fromfunction(f,(N,), dtype = int)
comb

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [76]:
#ndarray Attributes for Introspection
a = np.array(((1,0,1),(0,1,0)))
a.shape # returns the axis dimensions
        # 2 rows, 3 columns

(2, 3)

In [78]:
a.ndim # rank (number of dimensions)

2

In [80]:
a = np.array([[[1,2],[2,3]],[[2,1],[1,2]],[[2,1],[1,2]]])
a.shape # depth * length * width

(3, 2, 2)

In [86]:
a.size # total number of elements
a.dtype
a.data

12

In [4]:
#universal functions
x = np.linspace(1,5,5)
print(x)
x**3

[1. 2. 3. 4. 5.]


array([  1.,   8.,  27.,  64., 125.])

In [15]:
x = x-1
print(x)

[-2. -1.  0.  1.  2.]


In [11]:
np.sqrt(x-1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [16]:
print(-np.linspace(0,2,5))
y = np.exp(-np.linspace(0,2,5))
print(y)
print(x)
np.sin(x-y)

[-0.  -0.5 -1.  -1.5 -2. ]
[1.         0.60653066 0.36787944 0.22313016 0.13533528]
[-2. -1.  0.  1.  2.]


array([-0.14112001, -0.9993616 , -0.35963757,  0.7010507 ,  0.95713053])

In [23]:
#Matrix multiplication in numpy
a = np.array(((1,2),(2,1)))
b = a
a*b # Numpy always does elementwise multiplication

array([[1, 4],
       [4, 1]])

In [24]:
#a@b #matrix multiplication
b = a.T # transposing the "a" matrix
print(b)
np.matmul(a,b)

[[1 2]
 [2 1]]


array([[5, 4],
       [4, 5]])

In [25]:
print(a.dot(b)) #also try np.dot(a,b)
np.dot(a,b)

[[5 4]
 [4 5]]


array([[5, 4],
       [4, 5]])

In [26]:
np.dot?

In [27]:
# Comparision and logic opera
a = np.array([[1,2,3],[2,3,4]])
b = np.array([1,2])
np.dot(b,a)

array([ 5,  8, 11])

In [29]:
a>100

array([[False, False, False],
       [False, False, False]])

In [30]:
(a<10) | (a>100) # | for or

array([[ True,  True,  True],
       [ True,  True,  True]])

In [33]:
#flatten and ravel
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
b = a.flatten() # create an independent, flatten copy of a
print(a)
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [34]:
b[3] = 0
b

array([1, 2, 3, 0, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
c = a.ravel()
print(c)

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [38]:
c[3] = 0
c

array([1, 2, 3, 0, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a

array([[[1, 2, 3],
        [0, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
# resize and reshape
import numpy as np
a = np.linspace(1,8,8)
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [52]:
a.resize(2,2,2) # reshapes a in place, doesn't return anything
a

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [48]:
b = a.reshape(4,3)
b

ValueError: cannot reshape array of size 8 into shape (4,3)

In [49]:
b[0,0] = -88
b

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [53]:
a

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [59]:
#Transposing an array
a = np.linspace(1,16,16)
a = a.reshape(2,2,4)
print(a)
print(a.transpose()) # Think about it???
print(a.transpose().shape)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
[[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]
(4, 2, 2)


In [60]:
b = np.array([100,101,102,103])
b.transpose()

array([100, 101, 102, 103])

In [62]:
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])
d = np.dstack((a,b,c)) # stacks arrays vertically
# depth x Rows c cols
print(d.ndim)
print(d.ndim)

3
3


In [63]:
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])
d1 = np.vstack((a,b,c)) # stacks arrays horizontally
print(d1)
d1.shape

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]


(3, 4)

In [64]:
np.hstack((a,b,c))

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [65]:
np.dstack((a,b,c))

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [67]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [68]:
b = np.hsplit(a,2)
b

ValueError: array split does not result in an equal division

In [69]:
#indexing and slicing an array
a = np.linspace(10,16,6)
a

array([10. , 11.2, 12.4, 13.6, 14.8, 16. ])

In [70]:
a[1:5:2] # a stride of 2

array([11.2, 13.6])

In [71]:
a[2::2] # a stride of -2

array([12.4, 14.8])

In [72]:
a[2::-2] # a stride of -2

array([12.4, 10. ])

In [73]:
a = np.linspace(1,12,12).reshape(4,3)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [74]:
a[3,2]

12.0

In [75]:
a[:0] # everything in the third row

array([], shape=(0, 3), dtype=float64)

In [76]:
a[:,1] # the second column

array([ 2.,  5.,  8., 11.])

In [77]:
a = np.linspace(1,12,12).reshape(4,3)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [78]:
a[1:,1:2] # middle rows, second column onwards

array([[ 5.],
       [ 8.],
       [11.]])

In [79]:
a[3,1, ...]

array(11.)

In [80]:
a[:,1] = 0 # set all elements in the second column to zero
a

array([[ 1.,  0.,  3.],
       [ 4.,  0.,  6.],
       [ 7.,  0.,  9.],
       [10.,  0., 12.]])